### ISSUE TITLE
Squads roadmap

### ISSUE THREAD

**Issue by SanctusAnimus** [dota2unofficial/custom_hero_clash_issues#402]
- [x] All game mechanics working with squads player counts
- [x] Squads round layout (more creeps, harder creeps
- [ ] Squads map (larger arenas, less of them)
**NOTE**: changing squads map also requires us to change lots of hardcoded values (like arenas bounds for enforcer)
- [ ] UI tweaks
- [ ] Update leaderboards to show new map
- [ ] Fix Mouse over next round info not working. I'm guessing it broke because there is now two totems, not sure. 
- [ ] Double check gold is being rewarded correctly, like all players are getting the rewards for finishing the round early, for winning duels, winning bets etc. 
- [ ] Fix supporter perks not working

**Comment by AustraliaIsMyCity** [comment]
moved to megathread
